channels:
  - conda-forge
dependencies:
  - nbgitpuller
  - bokeh=1.4.0=py37_0
  - cartopy=0.17.0=py37h423102d_1009
  - datashader=0.9.0=py_0
  - geoviews=1.6.6=py_0
  - geoviews-core=1.6.6=py_0
  - holoviews=1.12.7=py_0
  - hvplot=0.5.2=py_0
  - metpy=0.11.1=py37_0
  - netcdf4=1.4.2=py37h808af73_0
  - panel=0.7.0=0
  - xarray=0.14.1=py_0
